#!/bin/bash
set -euo pipefail

version=""
non_interactive="no"
selected_profile=""
annovar_bind_path=""
phenosv_bind_path=""

for arg in "$@"; do
    case "$arg" in
        light)
            version="light"
            ;;
        --non-interactive)
            non_interactive="yes"
            ;;
        --profile=*)
            selected_profile="${arg#*=}"
            ;;
        --annovar-bind=*)
            annovar_bind_path="${arg#*=}"
            ;;
        --phenosv-bind=*)
            phenosv_bind_path="${arg#*=}"
            ;;
        *)
            echo "Unknown option: $arg" >&2
            echo "Usage: ./setup.sh [light] [--non-interactive] [--profile=<standard|slurm_singularity|local_singularity|local_docker>] [--annovar-bind=<path>] [--phenosv-bind=<path>]" >&2
            exit 1
            ;;
    esac
done

#After downloading annovar, download all the files necessary, and do the add annotation options

check_annovar="annovar"

# Check if the directory does NOT exist
if ! [ -d "$check_annovar" ]; then
    echo "Error: Directory '$check_annovar' not found. Aborting." >&2
    exit 1
fi

cd annovar

perl annotate_variation.pl -buildver hg38 -downdb cytoBand humandb/
perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar avsnp147 humandb/
perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar dbnsfp47a humandb/
perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar clinvar_20240917 humandb/
perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar refGene humandb/
perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar exac03 humandb/
perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar gnomad41_exome humandb/
perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar gnomad41_genome humandb/
perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar GTEx_v8_eQTL humandb/
perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar GTEx_v8_sQTL humandb/

cd ..



#Download phenosv, and change the paths as well


mkdir -p PhenoSV_model

cd PhenoSV_model

if [[ "$version" != "light" ]]
then
  if ! test -f "PhenosvFile.tar"; then
  echo "downloading PhenoSV files........"
  wget https://www.openbioinformatics.org/PhenoSV/PhenosvFile.tar
  fi
  echo "unzipping PhenosvFile.tar........"
  tar -xvf "PhenosvFile.tar"
  rm "PhenosvFile.tar"
else
  if ! test -f "PhenosvlightFile.tar"; then
  echo "downloading PhenoSV-light files........"
  wget https://www.openbioinformatics.org/PhenoSV/PhenosvlightFile.tar
  fi
  echo "unzipping PhenosvlightFile.tar........"
  tar -xvf "PhenosvlightFile.tar"
  rm "PhenosvlightFile.tar"
fi

wget https://github.com/WGLab/Phen2Gene/releases/download/1.1.0/H2GKBs.zip

unzip -q H2GKBs.zip
rm H2GKBs.zip

cd data

sed 's|/home/xu3/PhenoSV/data|/PhenoSV/train_data/data|g' featuremaster_scu1026.csv > features_set.csv

sed -i 's|/home/xu3/PhenoSV/data|/PhenoSV/train_data/data|g' features_set_light.csv

cd ../..

current_folder=$(pwd)

if [[ -z "$annovar_bind_path" ]]; then
    annovar_bind_path="${current_folder}/annovar"
fi
if [[ -z "$phenosv_bind_path" ]]; then
    phenosv_bind_path="${current_folder}/PhenoSV_model"
fi

if [[ "$non_interactive" == "no" && -z "$selected_profile" ]]; then
    cat <<'PROMPT'

Select your default runtime profile:
  1) standard (SLURM + Singularity)
  2) slurm_singularity (SLURM + Singularity)
  3) local_singularity (local + Singularity)
  4) local_docker (local + Docker)
PROMPT
    read -r -p "Enter choice [1-4] (default: 1): " profile_choice
    case "${profile_choice:-1}" in
        1) selected_profile="standard" ;;
        2) selected_profile="slurm_singularity" ;;
        3) selected_profile="local_singularity" ;;
        4) selected_profile="local_docker" ;;
        *) echo "Invalid profile choice: ${profile_choice}" >&2; exit 1 ;;
    esac
fi

if [[ -z "$selected_profile" ]]; then
    selected_profile="standard"
fi

if [[ "$non_interactive" == "no" ]]; then
    read -r -p "ANNOVAR bind host path [${annovar_bind_path}]: " user_annovar
    read -r -p "PhenoSV bind host path [${phenosv_bind_path}]: " user_phenosv
    annovar_bind_path="${user_annovar:-$annovar_bind_path}"
    phenosv_bind_path="${user_phenosv:-$phenosv_bind_path}"
fi

case "$selected_profile" in
    standard|slurm_singularity|local_singularity|local_docker) ;;
    *)
        echo "Invalid profile: $selected_profile" >&2
        exit 1
        ;;
esac

cat > .pipevar.user.config <<EOF
/*
 * Auto-generated by setup.sh
 * You can edit this file later to change default runtime behavior.
 */
manifest {
    defaultProfile = '${selected_profile}'
}
params {
    annovar_host_path = '${annovar_bind_path}'
    phenosv_host_path = '${phenosv_bind_path}'
}
EOF

echo
echo "Wrote local user config: ${current_folder}/.pipevar.user.config"
echo "  defaultProfile   = ${selected_profile}"
echo "  annovar_host_path= ${annovar_bind_path}"
echo "  phenosv_host_path= ${phenosv_bind_path}"
echo
echo "You can now run PipeVar without repeatedly passing bind paths or -profile."
